# replace "catw-farm" in the three targets below with your actual project(s)
apiVersion: deploy.cloud.google.com/v1
kind: DeliveryPipeline
metadata:
  name: pop-stats-pipeline-runthrough
description: pop-stats application delivery pipeline
serialPipeline:
 stages:
 - targetId: prod
   profiles:
   - prod
---
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: prod
description: prod cluster 1
gke:
  cluster: projects/catw-farm/locations/us-central1/clusters/prodcluster1