# Overview: build and create a release via Google Cloud Deploy for GKE
steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '.', '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/pop-stats/pop-stats', '-f', 'Dockerfile']
    dir: 'app'
images:
- us-central1-docker.pkg.dev/$PROJECT_ID/pop-stats/pop-stats
options:
  requestedVerifyOption: VERIFIED
    
