# replace "catw-farm" in the three targets below with your actual project(s)
apiVersion: deploy.cloud.google.com/v1
kind: DeliveryPipeline
metadata:
  name: pop-stats-pipeline-runthrough
description: pop-stats application delivery pipeline
serialPipeline:
 stages:
 - targetId: prod1
   profiles:
   - prod
   strategy:
    canary:
      runtimeConfig:
        kubernetes:
          serviceNetworking:
            service: "pop-stats"
            deployment: "pop-stats"
      canaryDeployment:
        percentages: [5]
        verify: true
 - targetId: prod2
   profiles:
   - prod
   strategy:
    canary:
      runtimeConfig:
        kubernetes:
          serviceNetworking:
            service: "pop-stats"
            deployment: "pop-stats"
      canaryDeployment:
        percentages: [5]
        verify: true
 - targetId: prod3
   profiles:
   - prod
   strategy:
    canary:
      runtimeConfig:
        kubernetes:
          serviceNetworking:
            service: "pop-stats"
            deployment: "pop-stats"
      canaryDeployment:
        percentages: [5]
        verify: true
---
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: prod
description: prod cluster 1
gke:
  cluster: projects/catw-farm/locations/us-central1/clusters/prodcluster1
---
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: prod2
description: prod cluster 2
gke:
  cluster: projects/catw-farm/locations/europe-west1/clusters/prodcluster2
---
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: prod3
description: prod cluster 3
gke:
  cluster: projects/catw-farm/locations/asia-northeast1/clusters/prodcluster3